import sqlite3

conn = sqlite3.connect('search_db.sqlite')
cur = conn.cursor()
#cur.execute('CREATE TABLE search_engines (title VARCHAR, link VARCHAR)')

cur.execute('INSERT INTO search_engines (title, link) values ("Example", "google")')


cur.execute('INSERT INTO search_engines (title, link) values ("Apple (India)", "https://www.apple.com/in/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple", "https://www.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Example", "google.com")')
cur.execute('INSERT INTO search_engines (title, link) values ("iPhone - Apple", "https://www.apple.com/iphone/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. - Wikipedia", "https://en.wikipedia.org/wiki/Apple_Inc.")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - YouTube", "https://www.youtube.com/user/Apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Card - Apple", "https://www.apple.com/apple-card")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes - Apple", "https://www.apple.com/itunes/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes - Upgrade to Get iTunes Now - Apple", "https://www.apple.com/itunes/download/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iPhone - Apple", "https://www.apple.com/iphone/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes - Apple (IN)", "https://www.apple.com/in/itunes/")')
cur.execute('INSERT INTO search_engines (title, link) values ("ExamManage your Apple ID - Appleple", "https://appleid.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple ID - Official Apple Support", "https://support.apple.com/en-in/apple-id")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Home | Facebook", "https://www.facebook.com/apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("@apple • Instagram photos and videos", "https://www.instagram.com/apple/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - YouTube", "https://www.youtube.com/channel/UCE_M8A5yxnLfW0KghEeajjw")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple (AAPL) Stock Price, Financials and News | Fortune 500", "http://fortune.com/fortune500/apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Events - Keynote March 2019 - Apple", "google.com")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Card - Apple", "https://www.apple.com/apple-card/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes", "https://www.apple.com/in/itunes/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Watch - Apple (IN)", "https://www.apple.com/in/watch/")')
cur.execute('INSERT INTO search_engines (title, link) values ("MacBook Pro - Apple (IN)", "https://www.apple.com/in/macbook-pro/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - YouTube", "https://www.youtube.com/channel/UCE_M8A5yxnLfW0KghEeajjwm")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Mobiles - Flipkart.com", "https://www.flipkart.com/mobiles/apple~brand/pr?sid=tyy,4io")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Simple English Wikipedia, the free encyclopedia", "https://simple.wikipedia.org/wiki/Apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("App Store - Apple", "https://www.apple.com/ios/app-store/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. - MarketWatch", "https://www.marketwatch.com/investing/stock/aapl")')
cur.execute('INSERT INTO search_engines (title, link) values ("App Store Downloads on iTunes - itunes.apple.com", "https://itunes.apple.com/US/genre/ios/id36")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes Movie Trailers", "https://trailers.apple.com/trailers/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iMac - Apple (IN", "https://www.apple.com/in/imac/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iPhone - Compare Models - Apple (IN)", "https://www.apple.com/in/iphone/compare/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple", "https://www.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("AAPL Stock Price - Apple Inc. Stock Quote (U.S.: Nasdaq ...", "https://www.marketwatch.com/investing/stock/aapl")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. - Wikipedia", "https://en.wikipedia.org/wiki/Apple_Inc.")')
cur.execute('INSERT INTO search_engines (title, link) values ("AAPL Stock Quote - Apple Inc. Common Stock Price - Nasdaq", "https://www.nasdaq.com/symbol/aapl")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple (@Apple) | Twitter", "https://twitter.com/Appl")')
cur.execute('INSERT INTO search_engines (title, link) values ("History of Apple Inc. - Wikipedia", "https://en.wikipedia.org/wiki/History_of_Apple_Inc.")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple (2018) - IMDb", "https://www.imdb.com/title/tt7245840/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Manage your Apple ID", "https://appleid.apple.com/#!&page=signin")')
cur.execute('INSERT INTO search_engines (title, link) values ("AAPL Stock Price & News - Apple Inc. - Wall Street Journal", "https://quotes.wsj.com/AAPL")')
cur.execute('INSERT INTO search_engines (title, link) values ("Manage your Apple ID - Apple", "https://appleid.apple.com/us/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Stock Price", "https://investor.apple.com/investor-relations/stock-price/m")')
cur.execute('INSERT INTO search_engines (title, link) values ("Contact - Official Apple Support", "https://support.apple.com/contact")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - CNET", "https://www.cnet.com/apple/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. Common Stock (AAPL) Historical Prices & Data ...", "https://www.nasdaq.com/symbol/aapl/historical")')
cur.execute('INSERT INTO search_engines (title, link) values ("United States - Jobs at Apple", "https://jobs.apple.com/en-us/search?location=united-states-USA")')
cur.execute('INSERT INTO search_engines (title, link) values ("AAPL Stock | APPLE Stock Price Today | Markets Insider", "https://markets.businessinsider.com/stocks/aapl-stock?op=1")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - YouTube", "https://www.youtube.com/user/Apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. (AAPL) Stock Price, Quote, History & News", "https://finance.yahoo.com/quote/AAPL/")')
cur.execute('INSERT INTO search_engines (title, link) values ("ara.apple.com - Apple Footer", "https://ara.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Find My iPhone on the App Store - itunes.apple.com", "https://itunes.apple.com/us/app/find-my-iphone/id376101648?mt=8")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Support | Verizon Wireless", "https://www.verizonwireless.com/support/apple/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Brand Store: Apple Products - Best Buy", "https://www.bestbuy.com/site/brands/apple/pcmcat128500050005.c?id=pcmcat128500050005")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Home | Facebook", "https://www.facebook.com/apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Investor Relations", "https://investor.apple.com/investor-relations/default.aspx")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Store on the App Store", "https://itunes.apple.com/us/app/apple-store/id375380948")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Developer", "https://developer.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("pple | Technology | The Guardian", "https://www.theguardian.com/technology/apple")')


cur.execute('INSERT INTO search_engines (title, link) values ("Apple (India)", "https://www.apple.com/in/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple", "https://www.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Example", "google.com")')
cur.execute('INSERT INTO search_engines (title, link) values ("iPhone - Apple", "https://www.apple.com/iphone/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. - Wikipedia", "https://en.wikipedia.org/wiki/Apple_Inc.")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - YouTube", "https://www.youtube.com/user/Apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Card - Apple", "https://www.apple.com/apple-card")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes - Apple", "https://www.apple.com/itunes/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes - Upgrade to Get iTunes Now - Apple", "https://www.apple.com/itunes/download/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iPhone - Apple", "https://www.apple.com/iphone/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes - Apple (IN)", "https://www.apple.com/in/itunes/")')
cur.execute('INSERT INTO search_engines (title, link) values ("ExamManage your Apple ID - Appleple", "https://appleid.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple ID - Official Apple Support", "https://support.apple.com/en-in/apple-id")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Home | Facebook", "https://www.facebook.com/apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("@apple • Instagram photos and videos", "https://www.instagram.com/apple/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - YouTube", "https://www.youtube.com/channel/UCE_M8A5yxnLfW0KghEeajjw")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple (AAPL) Stock Price, Financials and News | Fortune 500", "http://fortune.com/fortune500/apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Events - Keynote March 2019 - Apple", "google.com")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Card - Apple", "https://www.apple.com/apple-card/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes", "https://www.apple.com/in/itunes/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Watch - Apple (IN)", "https://www.apple.com/in/watch/")')
cur.execute('INSERT INTO search_engines (title, link) values ("MacBook Pro - Apple (IN)", "https://www.apple.com/in/macbook-pro/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - YouTube", "https://www.youtube.com/channel/UCE_M8A5yxnLfW0KghEeajjwm")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Mobiles - Flipkart.com", "https://www.flipkart.com/mobiles/apple~brand/pr?sid=tyy,4io")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Simple English Wikipedia, the free encyclopedia", "https://simple.wikipedia.org/wiki/Apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("App Store - Apple", "https://www.apple.com/ios/app-store/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. - MarketWatch", "https://www.marketwatch.com/investing/stock/aapl")')
cur.execute('INSERT INTO search_engines (title, link) values ("App Store Downloads on iTunes - itunes.apple.com", "https://itunes.apple.com/US/genre/ios/id36")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes Movie Trailers", "https://trailers.apple.com/trailers/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iMac - Apple (IN", "https://www.apple.com/in/imac/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iPhone - Compare Models - Apple (IN)", "https://www.apple.com/in/iphone/compare/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple", "https://www.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("AAPL Stock Price - Apple Inc. Stock Quote (U.S.: Nasdaq ...", "https://www.marketwatch.com/investing/stock/aapl")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. - Wikipedia", "https://en.wikipedia.org/wiki/Apple_Inc.")')
cur.execute('INSERT INTO search_engines (title, link) values ("AAPL Stock Quote - Apple Inc. Common Stock Price - Nasdaq", "https://www.nasdaq.com/symbol/aapl")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple (@Apple) | Twitter", "https://twitter.com/Appl")')
cur.execute('INSERT INTO search_engines (title, link) values ("History of Apple Inc. - Wikipedia", "https://en.wikipedia.org/wiki/History_of_Apple_Inc.")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple (2018) - IMDb", "https://www.imdb.com/title/tt7245840/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Manage your Apple ID", "https://appleid.apple.com/#!&page=signin")')
cur.execute('INSERT INTO search_engines (title, link) values ("AAPL Stock Price & News - Apple Inc. - Wall Street Journal", "https://quotes.wsj.com/AAPL")')
cur.execute('INSERT INTO search_engines (title, link) values ("Manage your Apple ID - Apple", "https://appleid.apple.com/us/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Stock Price", "https://investor.apple.com/investor-relations/stock-price/m")')
cur.execute('INSERT INTO search_engines (title, link) values ("Contact - Official Apple Support", "https://support.apple.com/contact")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - CNET", "https://www.cnet.com/apple/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. Common Stock (AAPL) Historical Prices & Data ...", "https://www.nasdaq.com/symbol/aapl/historical")')
cur.execute('INSERT INTO search_engines (title, link) values ("United States - Jobs at Apple", "https://jobs.apple.com/en-us/search?location=united-states-USA")')
cur.execute('INSERT INTO search_engines (title, link) values ("AAPL Stock | APPLE Stock Price Today | Markets Insider", "https://markets.businessinsider.com/stocks/aapl-stock?op=1")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - YouTube", "https://www.youtube.com/user/Apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. (AAPL) Stock Price, Quote, History & News", "https://finance.yahoo.com/quote/AAPL/")')
cur.execute('INSERT INTO search_engines (title, link) values ("ara.apple.com - Apple Footer", "https://ara.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Find My iPhone on the App Store - itunes.apple.com", "https://itunes.apple.com/us/app/find-my-iphone/id376101648?mt=8")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Support | Verizon Wireless", "https://www.verizonwireless.com/support/apple/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Brand Store: Apple Products - Best Buy", "https://www.bestbuy.com/site/brands/apple/pcmcat128500050005.c?id=pcmcat128500050005")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Home | Facebook", "https://www.facebook.com/apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Investor Relations", "https://investor.apple.com/investor-relations/default.aspx")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Store on the App Store", "https://itunes.apple.com/us/app/apple-store/id375380948")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Developer", "https://developer.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("pple | Technology | The Guardian", "https://www.theguardian.com/technology/apple")')

cur.execute('INSERT INTO search_engines (title, link) values ("Apple (India)", "https://www.apple.com/in/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple", "https://www.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Example", "google.com")')
cur.execute('INSERT INTO search_engines (title, link) values ("iPhone - Apple", "https://www.apple.com/iphone/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. - Wikipedia", "https://en.wikipedia.org/wiki/Apple_Inc.")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - YouTube", "https://www.youtube.com/user/Apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Card - Apple", "https://www.apple.com/apple-card")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes - Apple", "https://www.apple.com/itunes/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes - Upgrade to Get iTunes Now - Apple", "https://www.apple.com/itunes/download/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iPhone - Apple", "https://www.apple.com/iphone/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes - Apple (IN)", "https://www.apple.com/in/itunes/")')
cur.execute('INSERT INTO search_engines (title, link) values ("ExamManage your Apple ID - Appleple", "https://appleid.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple ID - Official Apple Support", "https://support.apple.com/en-in/apple-id")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Home | Facebook", "https://www.facebook.com/apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("@apple • Instagram photos and videos", "https://www.instagram.com/apple/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - YouTube", "https://www.youtube.com/channel/UCE_M8A5yxnLfW0KghEeajjw")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple (AAPL) Stock Price, Financials and News | Fortune 500", "http://fortune.com/fortune500/apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Events - Keynote March 2019 - Apple", "google.com")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Card - Apple", "https://www.apple.com/apple-card/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes", "https://www.apple.com/in/itunes/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Watch - Apple (IN)", "https://www.apple.com/in/watch/")')
cur.execute('INSERT INTO search_engines (title, link) values ("MacBook Pro - Apple (IN)", "https://www.apple.com/in/macbook-pro/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - YouTube", "https://www.youtube.com/channel/UCE_M8A5yxnLfW0KghEeajjwm")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Mobiles - Flipkart.com", "https://www.flipkart.com/mobiles/apple~brand/pr?sid=tyy,4io")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Simple English Wikipedia, the free encyclopedia", "https://simple.wikipedia.org/wiki/Apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("App Store - Apple", "https://www.apple.com/ios/app-store/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. - MarketWatch", "https://www.marketwatch.com/investing/stock/aapl")')
cur.execute('INSERT INTO search_engines (title, link) values ("App Store Downloads on iTunes - itunes.apple.com", "https://itunes.apple.com/US/genre/ios/id36")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes Movie Trailers", "https://trailers.apple.com/trailers/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iMac - Apple (IN", "https://www.apple.com/in/imac/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iPhone - Compare Models - Apple (IN)", "https://www.apple.com/in/iphone/compare/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple", "https://www.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("AAPL Stock Price - Apple Inc. Stock Quote (U.S.: Nasdaq ...", "https://www.marketwatch.com/investing/stock/aapl")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. - Wikipedia", "https://en.wikipedia.org/wiki/Apple_Inc.")')
cur.execute('INSERT INTO search_engines (title, link) values ("AAPL Stock Quote - Apple Inc. Common Stock Price - Nasdaq", "https://www.nasdaq.com/symbol/aapl")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple (@Apple) | Twitter", "https://twitter.com/Appl")')
cur.execute('INSERT INTO search_engines (title, link) values ("History of Apple Inc. - Wikipedia", "https://en.wikipedia.org/wiki/History_of_Apple_Inc.")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple (2018) - IMDb", "https://www.imdb.com/title/tt7245840/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Manage your Apple ID", "https://appleid.apple.com/#!&page=signin")')
cur.execute('INSERT INTO search_engines (title, link) values ("AAPL Stock Price & News - Apple Inc. - Wall Street Journal", "https://quotes.wsj.com/AAPL")')
cur.execute('INSERT INTO search_engines (title, link) values ("Manage your Apple ID - Apple", "https://appleid.apple.com/us/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Stock Price", "https://investor.apple.com/investor-relations/stock-price/m")')
cur.execute('INSERT INTO search_engines (title, link) values ("Contact - Official Apple Support", "https://support.apple.com/contact")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - CNET", "https://www.cnet.com/apple/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. Common Stock (AAPL) Historical Prices & Data ...", "https://www.nasdaq.com/symbol/aapl/historical")')
cur.execute('INSERT INTO search_engines (title, link) values ("United States - Jobs at Apple", "https://jobs.apple.com/en-us/search?location=united-states-USA")')
cur.execute('INSERT INTO search_engines (title, link) values ("AAPL Stock | APPLE Stock Price Today | Markets Insider", "https://markets.businessinsider.com/stocks/aapl-stock?op=1")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - YouTube", "https://www.youtube.com/user/Apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. (AAPL) Stock Price, Quote, History & News", "https://finance.yahoo.com/quote/AAPL/")')
cur.execute('INSERT INTO search_engines (title, link) values ("ara.apple.com - Apple Footer", "https://ara.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Find My iPhone on the App Store - itunes.apple.com", "https://itunes.apple.com/us/app/find-my-iphone/id376101648?mt=8")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Support | Verizon Wireless", "https://www.verizonwireless.com/support/apple/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Brand Store: Apple Products - Best Buy", "https://www.bestbuy.com/site/brands/apple/pcmcat128500050005.c?id=pcmcat128500050005")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Home | Facebook", "https://www.facebook.com/apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Investor Relations", "https://investor.apple.com/investor-relations/default.aspx")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Store on the App Store", "https://itunes.apple.com/us/app/apple-store/id375380948")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Developer", "https://developer.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("pple | Technology | The Guardian", "https://www.theguardian.com/technology/apple")')


cur.execute('INSERT INTO search_engines (title, link) values ("Apple (India)", "https://www.apple.com/in/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple", "https://www.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Example", "google.com")')
cur.execute('INSERT INTO search_engines (title, link) values ("iPhone - Apple", "https://www.apple.com/iphone/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. - Wikipedia", "https://en.wikipedia.org/wiki/Apple_Inc.")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - YouTube", "https://www.youtube.com/user/Apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Card - Apple", "https://www.apple.com/apple-card")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes - Apple", "https://www.apple.com/itunes/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes - Upgrade to Get iTunes Now - Apple", "https://www.apple.com/itunes/download/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iPhone - Apple", "https://www.apple.com/iphone/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes - Apple (IN)", "https://www.apple.com/in/itunes/")')
cur.execute('INSERT INTO search_engines (title, link) values ("ExamManage your Apple ID - Appleple", "https://appleid.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple ID - Official Apple Support", "https://support.apple.com/en-in/apple-id")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Home | Facebook", "https://www.facebook.com/apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("@apple • Instagram photos and videos", "https://www.instagram.com/apple/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - YouTube", "https://www.youtube.com/channel/UCE_M8A5yxnLfW0KghEeajjw")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple (AAPL) Stock Price, Financials and News | Fortune 500", "http://fortune.com/fortune500/apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Events - Keynote March 2019 - Apple", "google.com")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Card - Apple", "https://www.apple.com/apple-card/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes", "https://www.apple.com/in/itunes/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Watch - Apple (IN)", "https://www.apple.com/in/watch/")')
cur.execute('INSERT INTO search_engines (title, link) values ("MacBook Pro - Apple (IN)", "https://www.apple.com/in/macbook-pro/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - YouTube", "https://www.youtube.com/channel/UCE_M8A5yxnLfW0KghEeajjwm")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Mobiles - Flipkart.com", "https://www.flipkart.com/mobiles/apple~brand/pr?sid=tyy,4io")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Simple English Wikipedia, the free encyclopedia", "https://simple.wikipedia.org/wiki/Apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("App Store - Apple", "https://www.apple.com/ios/app-store/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. - MarketWatch", "https://www.marketwatch.com/investing/stock/aapl")')
cur.execute('INSERT INTO search_engines (title, link) values ("App Store Downloads on iTunes - itunes.apple.com", "https://itunes.apple.com/US/genre/ios/id36")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes Movie Trailers", "https://trailers.apple.com/trailers/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iMac - Apple (IN", "https://www.apple.com/in/imac/")')
cur.execute('INSERT INTO search_engines (title, link) values ("iPhone - Compare Models - Apple (IN)", "https://www.apple.com/in/iphone/compare/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple", "https://www.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("AAPL Stock Price - Apple Inc. Stock Quote (U.S.: Nasdaq ...", "https://www.marketwatch.com/investing/stock/aapl")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. - Wikipedia", "https://en.wikipedia.org/wiki/Apple_Inc.")')
cur.execute('INSERT INTO search_engines (title, link) values ("AAPL Stock Quote - Apple Inc. Common Stock Price - Nasdaq", "https://www.nasdaq.com/symbol/aapl")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple (@Apple) | Twitter", "https://twitter.com/Appl")')
cur.execute('INSERT INTO search_engines (title, link) values ("History of Apple Inc. - Wikipedia", "https://en.wikipedia.org/wiki/History_of_Apple_Inc.")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple (2018) - IMDb", "https://www.imdb.com/title/tt7245840/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Manage your Apple ID", "https://appleid.apple.com/#!&page=signin")')
cur.execute('INSERT INTO search_engines (title, link) values ("AAPL Stock Price & News - Apple Inc. - Wall Street Journal", "https://quotes.wsj.com/AAPL")')
cur.execute('INSERT INTO search_engines (title, link) values ("Manage your Apple ID - Apple", "https://appleid.apple.com/us/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Stock Price", "https://investor.apple.com/investor-relations/stock-price/m")')
cur.execute('INSERT INTO search_engines (title, link) values ("Contact - Official Apple Support", "https://support.apple.com/contact")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - CNET", "https://www.cnet.com/apple/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. Common Stock (AAPL) Historical Prices & Data ...", "https://www.nasdaq.com/symbol/aapl/historical")')
cur.execute('INSERT INTO search_engines (title, link) values ("United States - Jobs at Apple", "https://jobs.apple.com/en-us/search?location=united-states-USA")')
cur.execute('INSERT INTO search_engines (title, link) values ("AAPL Stock | APPLE Stock Price Today | Markets Insider", "https://markets.businessinsider.com/stocks/aapl-stock?op=1")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - YouTube", "https://www.youtube.com/user/Apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Inc. (AAPL) Stock Price, Quote, History & News", "https://finance.yahoo.com/quote/AAPL/")')
cur.execute('INSERT INTO search_engines (title, link) values ("ara.apple.com - Apple Footer", "https://ara.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Find My iPhone on the App Store - itunes.apple.com", "https://itunes.apple.com/us/app/find-my-iphone/id376101648?mt=8")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Support | Verizon Wireless", "https://www.verizonwireless.com/support/apple/")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Brand Store: Apple Products - Best Buy", "https://www.bestbuy.com/site/brands/apple/pcmcat128500050005.c?id=pcmcat128500050005")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Home | Facebook", "https://www.facebook.com/apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple - Investor Relations", "https://investor.apple.com/investor-relations/default.aspx")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Store on the App Store", "https://itunes.apple.com/us/app/apple-store/id375380948")')
cur.execute('INSERT INTO search_engines (title, link) values ("Apple Developer", "https://developer.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("pple | Technology | The Guardian", "https://www.theguardian.com/technology/apple")')


cur.execute('INSERT INTO search_engines (title, link) values ("Elon musk", "https://www.apple.com/in/")')
cur.execute('INSERT INTO search_engines (title, link) values ("steve jobs", "https://www.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("hack", "google.com")')
cur.execute('INSERT INTO search_engines (title, link) values ("mcirosfot - Apple", "https://www.apple.com/iphone/")')
cur.execute('INSERT INTO search_engines (title, link) values ("google Inc. - Wikipedia", "https://en.wikipedia.org/wiki/Apple_Inc.")')
cur.execute('INSERT INTO search_engines (title, link) values ("amazonb - YouTube", "https://www.youtube.com/user/Apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("modi Card - Apple", "https://www.apple.com/apple-card")')
cur.execute('INSERT INTO search_engines (title, link) values ("iTunes - Apple", "https://www.apple.com/itunes/")')
cur.execute('INSERT INTO search_engines (title, link) values ("bjp - Upgrade to Get iTunes Now - Apple", "https://www.apple.com/itunes/download/")')
cur.execute('INSERT INTO search_engines (title, link) values ("congress - Apple", "https://www.apple.com/iphone/")')
cur.execute('INSERT INTO search_engines (title, link) values ("party - Apple (IN)", "https://www.apple.com/in/itunes/")')
cur.execute('INSERT INTO search_engines (title, link) values ("ExamlaptopManage your Apple ID - Appleple", "https://appleid.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("flipkart ID - Official Apple Support", "https://support.apple.com/en-in/apple-id")')
cur.execute('INSERT INTO search_engines (title, link) values ("fb - Home | Facebook", "https://www.facebook.com/apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("@apple • Instagram photos and videos", "https://www.instagram.com/apple/")')
cur.execute('INSERT INTO search_engines (title, link) values ("pantnagar - YouTube", "https://www.youtube.com/channel/UCE_M8A5yxnLfW0KghEeajjw")')
cur.execute('INSERT INTO search_engines (title, link) values ("cot (AAPL) Stock Price, Financials and News | Fortune 500", "http://fortune.com/fortune500/apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("prabhu pant Events - Keynote March 2019 - Apple", "google.com")')
cur.execute('INSERT INTO search_engines (title, link) values ("amazon2 Card - Apple", "https://www.apple.com/apple-card/")')
cur.execute('INSERT INTO search_engines (title, link) values ("jeff bozes", "https://www.apple.com/in/itunes/")')
cur.execute('INSERT INTO search_engines (title, link) values ("bill gates - Apple (IN)", "https://www.apple.com/in/watch/")')
cur.execute('INSERT INTO search_engines (title, link) values ("spacx Pro - Apple (IN)", "https://www.apple.com/in/macbook-pro/")')
cur.execute('INSERT INTO search_engines (title, link) values ("tesla - YouTube", "https://www.youtube.com/channel/UCE_M8A5yxnLfW0KghEeajjwm")')
cur.execute('INSERT INTO search_engines (title, link) values ("tesla mortoer Mobiles - Flipkart.com", "https://www.flipkart.com/mobiles/apple~brand/pr?sid=tyy,4io")')
cur.execute('INSERT INTO search_engines (title, link) values ("nikola tesla - Simple English Wikipedia, the free encyclopedia", "https://simple.wikipedia.org/wiki/Apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("edison Store - Apple", "https://www.apple.com/ios/app-store/")')
cur.execute('INSERT INTO search_engines (title, link) values ("farady Inc. - MarketWatch", "https://www.marketwatch.com/investing/stock/aapl")')
cur.execute('INSERT INTO search_engines (title, link) values ("App Store Downloads on iTunes - itunes.apple.com", "https://itunes.apple.com/US/genre/ios/id36")')
cur.execute('INSERT INTO search_engines (title, link) values ("jobs Movie Trailers", "https://trailers.apple.com/trailers/")')
cur.execute('INSERT INTO search_engines (title, link) values ("android - Apple (IN", "https://www.apple.com/in/imac/")')
cur.execute('INSERT INTO search_engines (title, link) values ("computer - Compare Models - Apple (IN)", "https://www.apple.com/in/iphone/compare/")')
cur.execute('INSERT INTO search_engines (title, link) values ("mobile", "https://www.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("urich Stock Price - Apple Inc. Stock Quote (U.S.: Nasdaq ...", "https://www.marketwatch.com/investing/stock/aapl")')
cur.execute('INSERT INTO search_engines (title, link) values ("germany Inc. - Wikipedia", "https://en.wikipedia.org/wiki/Apple_Inc.")')
cur.execute('INSERT INTO search_engines (title, link) values ("football Stock Quote - Apple Inc. Common Stock Price - Nasdaq", "https://www.nasdaq.com/symbol/aapl")')
cur.execute('INSERT INTO search_engines (title, link) values ("ronaldo (@Apple) | Twitter", "https://twitter.com/Appl")')
cur.execute('INSERT INTO search_engines (title, link) values ("messi of Apple Inc. - Wikipedia", "https://en.wikipedia.org/wiki/History_of_Apple_Inc.")')
cur.execute('INSERT INTO search_engines (title, link) values ("hazrad (2018) - IMDb", "https://www.imdb.com/title/tt7245840/")')
cur.execute('INSERT INTO search_engines (title, link) values ("chelsea your Apple ID", "https://appleid.apple.com/#!&page=signin")')
cur.execute('INSERT INTO search_engines (title, link) values ("lampard Stock Price & News - Apple Inc. - Wall Street Journal", "https://quotes.wsj.com/AAPL")')
cur.execute('INSERT INTO search_engines (title, link) values ("terry your Apple ID - Apple", "https://appleid.apple.com/us/")')
cur.execute('INSERT INTO search_engines (title, link) values ("champions league - Stock Price", "https://investor.apple.com/investor-relations/stock-price/m")')
cur.execute('INSERT INTO search_engines (title, link) values ("europa - Official Apple Support", "https://support.apple.com/contact")')
cur.execute('INSERT INTO search_engines (title, link) values ("moruinho - CNET", "https://www.cnet.com/apple/")')
cur.execute('INSERT INTO search_engines (title, link) values ("salah Inc. Common Stock (AAPL) Historical Prices & Data ...", "https://www.nasdaq.com/symbol/aapl/historical")')
cur.execute('INSERT INTO search_engines (title, link) values ("uniktedknidngas States - Jobs at Apple", "https://jobs.apple.com/en-us/search?location=united-states-USA")')
cur.execute('INSERT INTO search_engines (title, link) values ("meghan Stock | APPLE Stock Price Today | Markets Insider", "https://markets.businessinsider.com/stocks/aapl-stock?op=1")')
cur.execute('INSERT INTO search_engines (title, link) values ("prince - YouTube", "https://www.youtube.com/user/Apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("acer Inc. (AAPL) Stock Price, Quote, History & News", "https://finance.yahoo.com/quote/AAPL/")')
cur.execute('INSERT INTO search_engines (title, link) values ("ases.apple.com - Apple Footer", "https://ara.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("locate My iPhone on the App Store - itunes.apple.com", "https://itunes.apple.com/us/app/find-my-iphone/id376101648?mt=8")')
cur.execute('INSERT INTO search_engines (title, link) values ("oragne Support | Verizon Wireless", "https://www.verizonwireless.com/support/apple/")')
cur.execute('INSERT INTO search_engines (title, link) values ("netherland Brand Store: Apple Products - Best Buy", "https://www.bestbuy.com/site/brands/apple/pcmcat128500050005.c?id=pcmcat128500050005")')
cur.execute('INSERT INTO search_engines (title, link) values ("portufgal - Home | Facebook", "https://www.facebook.com/apple")')
cur.execute('INSERT INTO search_engines (title, link) values ("spain - Investor Relations", "https://investor.apple.com/investor-relations/default.aspx")')
cur.execute('INSERT INTO search_engines (title, link) values ("france Store on the App Store", "https://itunes.apple.com/us/app/apple-store/id375380948")')
cur.execute('INSERT INTO search_engines (title, link) values ("india Developer", "https://developer.apple.com/")')
cur.execute('INSERT INTO search_engines (title, link) values ("nepal | Technology | The Guardian", "https://www.theguardian.com/technology/apple")')


conn.commit()

conn.close()
